language: android
jdk:
  - oraclejdk8

env:
  global:
   - ANDROID_API_LEVEL=25
   - EMULATOR_API_LEVEL=21
   - ANDROID_BUILD_TOOLS_VERSION=25.0.3
   - EMULATOR_TAG=google_apis
   - EMULATOR_ABI=armeabi-v7a
   - TOOLS=${ANDROID_HOME}/tools
   - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
   - ADB_INSTALL_TIMEOUT=20

android:
  components:
    - tools
    - platform-tools
    - android-25
    - extra
    - build-tools-25.0.1
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-android-25

branches:
  only:
  - master
  - develop

before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    - export EMULATOR="system-images;android-${EMULATOR_API_LEVEL};${EMULATOR_TAG};${EMULATOR_ABI}"

before_script:
    - echo no | avdmanager create avd -n test -k "${EMULATOR}" -f --abi "${EMULATOR_ABI}" --tag "${EMULATOR_TAG}"
    - emulator -avd test -engine classic -skin 768x1280 -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    - if [ "$TRAVIS_BRANCH" = "develop" ]; then echo "./gradlew test"; else ./gradlew assembleRelease; fi
    - ./gradlew connectedDebugAndroidTest
