language: android
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-25
    - extra
    - build-tools-25.0.1
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-android-25

branches:
  only:
  - master
  - develop

before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
    - if [ "$TRAVIS_BRANCH" = "develop" ]; then echo "./gradlew test"; else ./gradlew assembleRelease; fi
